### ISSUE TITLE
flat_render_iterative not passing basic data types test

### ISSUE THREAD

**Issue by ghwilliams** [ghwilliams/Eiffel_FLAT_RENDERER#1]
The new iterative version for the dump routine is not passing the test for basic data types. 
See the test output below:

Executing 4 tests
```JavaScript
test_1 (FLAT_RENDERER_TEST_SET): pass
ad_hoc_test (FLAT_RENDERER_TEST_SET): pass
test_2 (FLAT_RENDERER_TEST_SET): pass
basic_types_tests (FLAT_RENDERER_TEST_SET): FAIL (not_empty)
```
	on_prepare: ok
	test routine: exceptional (Precondition violation in FLAT_RENDERER.dump_iterable_iterative)
	on_clean: ok

Execution complete

**Comment by ljr1981** [comment]
BTW: This comment is going to be me being "Captain Whitespace!"

By convention of coding style, you will find that we add a single space between a class name and the opening square bracket for the list of Generics. See what I mean in the illustration below.

![image](https://user-images.githubusercontent.com/1668502/44722762-10e71580-aa9c-11e8-93aa-7f923bc7fe9c.png)

**Comment by ghwilliams** [comment]
I will start doing "Prettify class Ctrl+Shift+P". It will solve this issue
definitely

Very thanks

**Comment by ghwilliams** [comment]
Passed all tests now. But I replaced the first test for the basic types:
```JavaScript
assert_strings_equal ("basic_1_string", "1:b,2:l,3:a,4:h", l_renderer.dump ("blah"))
```
by
```JavaScript
assert_strings_equal ("basic_1_string", "blah", l_renderer.dump ("blah"))
```

**Comment by ljr1981** [comment]
The only comment to make is this: The STRING type is actually ITERABLE, which means it is an iterable collection of CHARACTER objects, which ought (rightfully) result in the "expected" that you replaced. However, to our end user or library reuse consumer, this may not make sense to them and your replacement might be better. Why? Because the outputs of the other basic types are precisely what one would expect. So—while technically wrong, the normal expectation of the consuming user programmer might be better met by your solution!
